### ISSUE TITLE
kubernetes

### ISSUE THREAD

**Issue by HugoDoyon** [shirhatti/dotnet-monitor-demo#2]
Hi Sourabh,

I have follow all you video and setup instructions (readme.md). I have setup a deployment in K8s accordingly. Unfortunately it seem that something is broken from inside of the "mcr.microsoft.com/dotnet/nightly/monitor" image.

After setting up the port forward, I am able to get from http://localhost:7000/metrics endpoint successful result.

However, every time I query /dump /logs or any other endpoints I have no result with a blank page!

Here the deployment YAML file that I am using:

```
apiVersion: v1
kind: Service
metadata:
  name: dotnet-hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-hello-world
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metric
    port: 52325
    targetPort: 52325    
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-hello-world
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "52325"
      labels:
        app: dotnet-hello-world
    spec:
      volumes:
      - name: diagnostics
        emptyDir: {}
      containers:
      - name: server
        image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /tmp
            name: diagnostics
      - name: sidecar
        image: mcr.microsoft.com/dotnet/nightly/monitor
        ports:
        - containerPort: 52325
        args: ["--urls", "http://*:52323", "--metricUrls", "http://*:52325"]
        volumeMounts:
          - name: diagnostics
            mountPath: /tmp
```

Could you help me fix this issue?
